# PostgreSQL.

development:
  adapter: postgresql
  encoding: unicode
  database: baseball_stats_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: baseball_stats_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: baseball_stats_production
  pool: 5
  username:
  password:
